FROM registry.fedoraproject.org/fedora:39 AS builder
RUN dnf -y install golang make
COPY . /src
RUN cd /src && make && make install DESTDIR=/instroot

FROM registry.fedoraproject.org/fedora:39
RUN dnf install -y osbuild osbuild-ostree && dnf clean all
COPY --from=builder images/osbuild-deploy-container /usr/bin/osbuild-deploy-container
COPY entrypoint.sh /
COPY --from=builder images/dnf-json .

ENTRYPOINT ["/entrypoint.sh"]
VOLUME /output
VOLUME /store
VOLUME /rpmmd

