FROM registry.fedoraproject.org/fedora:42 AS osbuild-builder
# build osbuild RPMs
RUN dnf install -y rpm-build dnf-plugins-core git-core
COPY --from=osbuild . /build
WORKDIR /build
RUN dnf builddep -y osbuild.spec
RUN git config --global --add safe.directory /build
RUN make rpm


FROM registry.fedoraproject.org/fedora:42 AS bib-builder
# replace osbuild/images dependency and build bib
RUN dnf install -y git-core golang gpgme-devel libassuan-devel
COPY --from=images . /build/images
COPY bib /build/bib
COPY build.sh /build

WORKDIR /build/bib
RUN go mod edit -replace github.com/osbuild/images=../images
RUN go mod tidy
WORKDIR /build
RUN ./build.sh


FROM registry.fedoraproject.org/fedora:42
COPY --from=osbuild-builder /build/rpmbuild/RPMS/noarch/*.rpm /rpms/
COPY ./package-requires.txt .
RUN grep -vE '^#' package-requires.txt | xargs dnf install -y && rm -f package-requires.txt && dnf install -y /rpms/*.rpm && dnf clean all
COPY --from=bib-builder /build/bin/bootc-image-builder /usr/bin/bootc-image-builder

ENTRYPOINT ["/usr/bin/bootc-image-builder"]
VOLUME /output
WORKDIR /output
VOLUME /store
VOLUME /rpmmd
