name: Build containers

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:
  # for merge queue
  merge_group:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: "latest"
          containerfiles: Containerfile

      - name: Log in to the Container registry
        if: ${{ (github.event_name == 'workflow_dispatch' }}
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Repository
        if: ${{ (github.event_name == 'workflow_dispatch' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: "latest"
          registry: ${{ env.REGISTRY }}
