---
name: Build containers

"on":
  pull_request:
    branches:
      - main
      - rhel-*
  workflow_dispatch:
  # for merge queue
  merge_group:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build image
        uses: redhat-actions/buildah-build@v3
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: "latest"
          containerfiles: Containerfile
